Make compatible with a wider range of completion package versions
This updates our modified hooks to match the latest hooks generated by
symfony-console-completion which brings in some minor bug fixes and adds
support for multi-word completions from symfony-console-completion 0.10.x.

I've given a wide version constraint to play nicely with other packages
that might share a dependency in the global composer.json. The min and
max versions have both been tested in BASH and ZSH and work correctly.
I assume everything in between does too as there haven't been any
breaking hook changes between.

diff --git a/hooks/bash-completion b/hooks/bash-completion
--- a/hooks/bash-completion
+++ b/hooks/bash-completion
@@ -2,15 +2,15 @@
 # Composer will only load plugins when a valid composer.json is in its working directory,
 # so  for this hack to work, we are always running the completion command in ~/.composer
 function _composercomplete {
-    local CMDLINE_CONTENTS="$COMP_LINE"
-    local CMDLINE_CURSOR_INDEX="$COMP_POINT"
+    local CMDLINE_CONTENTS="$COMP_LINE";
+    local CMDLINE_CURSOR_INDEX="$COMP_POINT";
     local CMDLINE_WORDBREAKS="$COMP_WORDBREAKS";
-    local COMPOSER_CWD="$PWD"
 
-    export CMDLINE_CONTENTS CMDLINE_CURSOR_INDEX CMDLINE_WORDBREAKS COMPOSER_CWD
+    export CMDLINE_CONTENTS CMDLINE_CURSOR_INDEX CMDLINE_WORDBREAKS;
 
-	# Run using the program being completed
-	local composer="$1"
+    # Run using the program being completed
+    local COMPOSER_CWD="$PWD";
+    local composer="$1"
 
     # Query and cache where the global composer.json lives
     if [ -z "$_composer_config_dir" ]; then
@@ -18,13 +18,24 @@ function _composercomplete {
     fi
 
     local RESULT STATUS;
-    RESULT=$(cd "$_composer_config_dir" && $composer depends _completion);
+
+    local IFS=$'\n';
+
+    RESULT="$(cd "$_composer_config_dir" && $composer depends _completion --shell-type bash </dev/null)";
     STATUS=$?;
 
-    local cur;
+    local cur mail_check_backup;
+
+    mail_check_backup=$MAILCHECK;
+    MAILCHECK=-1;
+
     _get_comp_words_by_ref -n : cur;
 
-    if [ $STATUS -ne 0 ]; then
+    if [ $STATUS -eq 200 ]; then
+        compopt -o default;
+        return 0;
+
+    elif [ $STATUS -ne 0 ]; then
         echo -e "$RESULT";
         return $?;
     fi;
@@ -32,6 +43,13 @@ function _composercomplete {
     COMPREPLY=(`compgen -W "$RESULT" -- $cur`);
 
     __ltrim_colon_completions "$cur";
+
+    MAILCHECK=mail_check_backup;
 };
 
-complete -F _composercomplete composer;
+if [ "$(type -t _get_comp_words_by_ref)" == "function" ]; then
+    complete -F _composercomplete composer;
+else
+    >&2 echo "Completion was not registered for composer:";
+    >&2 echo "The 'bash-completion' package is required but doesn't appear to be installed.";
+fi;
